require:
  - ts-node/register/transpile-only
additionalResolvers:
  - ./src/mesh-resolvers.ts
serve:
  port: 5000
  playground: true
  endpoint: "/graphql"
  cors:
    origin: "http://localhost:3000"

sources:
  - name: Login
    handler:
      graphql:
        endpoint: http://localhost:4000/graphql
  - name: Rss
    handler:
      graphql:
        endpoint: http://localhost:4001/graphql
